spring:
  application:
    name: course-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
  sql:
    init:
      data-locations: classpath:courses.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      students:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      students:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError