#properties
#mongodb://localhost:27017
#spring.data.mongodb.uri=mongodb://localhost:27017/pruebasmongo (crear bdd ANTES)
spring:
  application:
    name: movie-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stephieandrade/configuration-files-exam
