spring:
  application:
    name: student-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
  sql:
    init:
      data-locations: classpath:student.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
